apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: pulumi-kubernetes-operator
  namespace: pulumi-kubernetes-operator
spec:
  interval: 5m0s
  type: oci
  url: oci://ghcr.io/pulumi/helm-charts
