apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pulumi-kubernetes-operator
  namespace: pulumi-kubernetes-operator
spec:
  interval: 5m0s
  chart:
    spec:
      chart: pulumi-kubernetes-operator
      version: "2.0.0"
      sourceRef:
        kind: HelmRepository
        name: pulumi-kubernetes-operator
        namespace: pulumi-kubernetes-operator
      interval: 5m0s
  values:
    # Use chart defaults - minimal configuration
    # All values can be overridden in environment overlays
