apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pulumi-operator
  namespace: pulumi-kubernetes-operator
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infrastructure/prod/pulumi-operator
  prune: true
  wait: true
  timeout: 5m0s
